version: '3.3'

services:
  app:
    build: .
    container_name: krsirrigationsystem_frontend
    env_file:
      - .env    
    ports:
      - ${APP_PORT}:80
    networks:
      frontend:
        ipv4_address: 173.23.2.14        
    restart: always 
    labels:
        traefik.enable: "true"
        traefik.http.middlewares.opifrontend-redirects.redirectscheme.scheme: "https"
        traefik.http.middlewares.opifrontend-redirects.redirectscheme.permanent: "true"
        traefik.http.routers.opifrontend-http_catchall.rule: "HostRegexp(`{any:.+}`)"
        traefik.http.routers.opifrontend-http_catchall.entrypoints: 'web'
        traefik.http.routers.opifrontend-http_catchall.middlewares: "opifrontend-redirects"
        traefik.http.middlewares.opifrontend-webheaders.headers.customrequestheaders.Connection: "keep-alive"
        traefik.http.middlewares.opifrontend-webheaders.headers.customresponseheaders.Cache-Control: "public, max-age"
        traefik.http.middlewares.opifrontend-webheaders.headers.customresponseheaders.X-StudioCubo: "OBSERVATORIO-OPI-FRONTEND"
        traefik.http.routers.opifrontend-https.middlewares: "opifrontend-webheaders"
        traefik.http.routers.opifrontend-https.entrypoints: "websecure"
        traefik.http.routers.opifrontend-https.rule: "Host(`homologacao.povosisolados.org`)"
        traefik.http.routers.opifrontend-https.tls: "true"
networks:
    frontend:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 173.23.2.0/24

