version: '3'
services:
  app:
    container_name: krsirrigationsystem_controller
    build: .
    restart: always
    env_file:
      - .env
    ports:
       - '${FORWARD_APP_PORT}:${APP_PORT}'
    volumes:
      - ./storage:/app/storage
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.subsAPI-redirects.redirectscheme.scheme: "https"
      traefik.http.middlewares.subsAPI-redirects.redirectscheme.permanent: "true"    
      traefik.http.routers.subsAPI-http_catchall.rule: "Host(`subscription-api.epbr.com.br`)"
      traefik.http.routers.subsAPI-http_catchall.entrypoints: 'web'
      traefik.http.routers.subsAPI-http_catchall.middlewares: "subsAPI-redirects"      
      traefik.http.middlewares.subsAPI-webheaders.headers.customrequestheaders.Connection: "keep-alive"
      traefik.http.middlewares.subsAPI-webheaders.headers.customresponseheaders.Cache-Control: "public, max-age"
      traefik.http.routers.subsAPI-https.middlewares: "subsAPI-webheaders"
      traefik.http.routers.subsAPI-https.entrypoints: "websecure"
      traefik.http.routers.subsAPI-https.rule: "Host(`subscription-api.epbr.com.br`)"
      traefik.http.routers.subsAPI-https.tls: "true"

networks:
    backend:
